language: node_js
sudo: required
services:
  - docker
dist: trusty
node_js:
  - 6

env:
  global:
    - TAG=travis-${TRAVIS_BUILD_NUMBER}

before_script:
  - docker-compose build

script:
  - docker-compose run sh 'npm i --only=dev && npm run test'
  - cd tests && npm i
  - docker-compose run --rm nightwatch
