language: node_js
sudo: required
services:
  - docker
dist: trusty
node_js:
  - 6

env:
  global:
    - TAG=travis-${TRAVIS_BUILD_NUMBER}

install:
  - TAG=latest docker-compose pull
  - docker-compose build
  - sh -c 'cd tests && npm i'

before_script:
  - cp example.config.js config.js

script:
  - docker-compose up -d newdat && sleep 10
  - docker-compose run --rm app sh 'npm i --only=dev && npm run test'
  - docker-compose run --rm nightwatch
